# Generated by Django 5.2.5 on 2025-08-27 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_categorie', models.CharField(choices=[('materiel', 'Matériel'), ('main_oeuvre', "Main d'œuvre"), ('transport', 'Transport'), ('etude', 'Étude')], max_length=20)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('entreprise', models.CharField(blank=True, max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('couleur', models.CharField(default='#007bff', max_length=7)),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
            },
        ),
        migrations.CreateModel(
            name='DemandeElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300)),
                ('caracteristiques', models.TextField(blank=True)),
                ('unite', models.CharField(choices=[('u', 'Unité'), ('ml', 'Mètre linéaire'), ('m2', 'm²'), ('m3', 'm³'), ('kg', 'Kilogramme'), ('h', 'Heure'), ('j', 'Jour'), ('ens', 'Ensemble'), ('ff', 'Forfait')], default='u', max_length=10)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('prix_unitaire_admin', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('commentaire_admin', models.TextField(blank=True, help_text="Commentaire de l'administrateur")),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.categorie')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.discipline')),
            ],
            options={
                'verbose_name': "Demande d'élément",
                'verbose_name_plural': "Demandes d'éléments",
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('designation', models.CharField(max_length=300)),
                ('caracteristiques', models.TextField(blank=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unite', models.CharField(choices=[('u', 'Unité'), ('ml', 'Mètre linéaire'), ('m2', 'm²'), ('m3', 'm³'), ('kg', 'Kilogramme'), ('h', 'Heure'), ('j', 'Jour'), ('ens', 'Ensemble'), ('ff', 'Forfait')], default='u', max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.categorie')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.discipline')),
            ],
            options={
                'verbose_name': 'Élément',
                'verbose_name_plural': 'Éléments',
                'ordering': ['numero', 'designation'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('client_nom', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='estimation.client')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='EstimationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_total_materiel', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cout_total_main_oeuvre', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cout_total_transport', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cout_total_etude', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tva_taux', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('cout_total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tva_montant', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cout_total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estimation.projet')),
            ],
            options={
                'verbose_name': "Résumé d'estimation",
                'verbose_name_plural': "Résumés d'estimation",
            },
        ),
        migrations.CreateModel(
            name='EstimationElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('prix_unitaire_fixe', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('demande_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimation.demandeelement')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimation.element')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.projet')),
            ],
            options={
                'verbose_name': "Élément d'estimation",
                'verbose_name_plural': "Éléments d'estimation",
            },
        ),
        migrations.AddField(
            model_name='demandeelement',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.projet'),
        ),
        migrations.CreateModel(
            name='CalculSablage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(max_length=50)),
                ('diametre_dn', models.IntegerField(help_text='DN en mm')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('surface_unitaire', models.DecimalField(decimal_places=6, help_text='Surface unitaire en m²', max_digits=10)),
                ('surface_totale', models.DecimalField(decimal_places=6, help_text='Surface totale en m²', max_digits=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.projet')),
            ],
            options={
                'verbose_name': 'Calcul de sablage',
                'verbose_name_plural': 'Calculs de sablage',
            },
        ),
        migrations.CreateModel(
            name='SessionSablage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_globale', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('prix_unitaire_m2', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('cout_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('valide', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('calculs', models.ManyToManyField(blank=True, to='estimation.calculsablage')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.projet')),
            ],
            options={
                'verbose_name': 'Session de sablage',
                'verbose_name_plural': 'Sessions de sablage',
            },
        ),
    ]
