# Generated by Django 5.2.5 on 2025-09-04 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('symbole', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Unités',
                'ordering': ['libelle'],
            },
        ),
        migrations.RemoveField(
            model_name='demandeelement',
            name='unite_personnalisee',
        ),
        migrations.RemoveField(
            model_name='element',
            name='unite_personnalisee',
        ),
        migrations.AlterField(
            model_name='calculsablage',
            name='surface_totale',
            field=models.DecimalField(decimal_places=6, help_text='m² total', max_digits=15),
        ),
        migrations.AlterField(
            model_name='calculsablage',
            name='surface_unitaire',
            field=models.DecimalField(decimal_places=6, help_text='m² / unité', max_digits=10),
        ),
        migrations.AlterField(
            model_name='demandeelement',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='estimation.unite'),
        ),
        migrations.AlterField(
            model_name='element',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='estimation.unite'),
        ),
    ]
